services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: locatrust
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 4307:3306
    volumes:
      - ./mysql:/var/lib/mysql
  frontend:
    container_name: locatrust-front
    build:
      context: ./front
    ports:
      - "3000:3000"

  backend:
    container_name: locatrust-back
    build:
      context: ./back
    ports:
      - "8082:80"
    volumes:
      - ./back/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./back:/var/www 
    depends_on:
      - mysql
  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - 8899:80
  